version: '3.7'

services:
  reverse-proxy:
    image: traefik:v2.11
    command: --api.insecure=true --providers.docker
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
#      - ./traefik/traefik.toml:/etc/traefik/traefik.toml
    networks:
      - traefik-public

  whoami:
    image: traefik/whoami
    labels:
      - "traefik.http.routers.whoami.rule=Host(`whoami.localhost`)"

  app:
    image: node:18.19.1
    build:
      context: ./app/
      dockerfile: ./Dockerfile
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nodejs-app.rule=Host(`localhost`)"
      - "traefik.http.services.nodejs-app.loadbalancer.server.port=3000"
    ports:
      - "3000:3000"
    volumes:
      - ./app:/app
    networks:
      - traefik-public

networks:
  traefik-public:

